### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by anthonyrivas**

### CODE REVIEW

**Review by kingluddite — CHANGES_REQUESTED** [review]
H is capitalized

**Comment by anthonyrivas** [comment]
Fixed that H, @kingluddite can you please approve?

**Review by kingluddite — APPROVED** [review]
Awesome job!

**Review by kingluddite — APPROVED** [review]

**Review by kingluddite — APPROVED** [review]

**Review by kingluddite — COMMENTED** [review]
test

**Review by kingluddite — APPROVED** [review]

**Review by kingluddite — APPROVED** [review]

**Review by kingluddite — APPROVED** [review]

**Review by kingluddite — APPROVED** [review]

**Review by kingluddite — APPROVED** [review]

**Pull request closed without merging**
